### ISSUE TITLE
feat: citadel knighting round

### ISSUE THREAD

**Issue by axejintao** [Badger-Finance/v2-ui#1644]
# Summary

Enable a Ctiadel DAO presale functionality. This specifically should implement interaction with [Knighting Round](https://github.com/Citadel-DAO/citadel-contracts/blob/main/src/KnightingRound.sol).

## Requirements

- Support two separate KnightingRound targeting two separate contracts

Some requirements are listed as tasks per older docs.

## Tasks

- [x] #1645
- [x] #1646
- [x] #1647
- [ ] #1648

**Comment by eliobricenov** [comment]
closing as this will be handled in the citadel app
