### ISSUE TITLE
task: hide not available vault data if using fallback vaults

### ISSUE THREAD

**Issue by eliobricenov** [Badger-Finance/v2-ui#1783]
**related to https://github.com/Badger-Finance/v2-ui/pull/1755#discussion_r807317629**

Currently, we're using an adapter class to transform the vaults data received from the SDK (`RegitryVault`) to the model used in the API (`Vault`). This is only partially possible because the `RegitryVault` model has less information than `Vault`, as a result, some values are added as default such as the protocol and boost type.

IMO, it'd be better if we hide this information because it can cause confusion.

Additionally, we should add a fallback image for the vaults icons, because the icons files are named after the `vaultAssset` property from the API which is not available in the SDK either.

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/38574891/154510689-9af07d27-f015-4b0c-80d5-fb9ee6298e90.png">
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/38574891/154510787-8186c21a-5f18-4eef-af2e-cf82cf62b945.png">

**Comment by mrbasado** [comment]
seems to be done
