### ISSUE TITLE
UI Library - Vaults Detailed Page

### ISSUE THREAD

**Issue by axejintao** [Badger-Finance/v2-ui#1918]
[Figma](https://www.figma.com/file/6zYgzhJFnX0bNAk7ohEH4T/Badger-App?node-id=2873%3A251540)

- [ ] Resources: Remove the link ''Get Deposit tokens'' in all vaults, because this link is now shown in the ''Steps to Deposit''

**Comment by axejintao** [comment]
https://www.figma.com/file/6zYgzhJFnX0bNAk7ohEH4T/Badger-App?node-id=7621%3A343469

**Comment by mrbasado** [comment]
update: remove the "Get Deposit Token" link from vault detail page 👍
