### ISSUE TITLE
Discord Bug Report: Tritium

### ISSUE THREAD

**Issue by mitche50** [Badger-Finance/v2-ui#1978]
Reported on: 2022-03-30T06:08:42.729000+00:00
Bug Description:
Just noticed that links like this: https://app.badger.com/setts/0xdao-bveoxd don't work.  It takes a while to load the setts and then goes back to the sett list.  Would love to be able to reference individual pages on FTM cuz there's a lot there.

Attachments:

**Comment by eliobricenov** [comment]
Interesting issue, the vault is not loading because the default network is mainnet, and the URL vault is in FTM. 

We will need to implement some query parameters for the chain.

**Comment by Tritium-VLK** [comment]
Actually the new UI has filters.  It would be great to be able to have URL's with query parms on any filter.

So for example

app.badger.com?chain=FTM&Platform=OXD

or app.badger.com?chain=ETH&Rewards=Bitcoin

**Comment by eliobricenov** [comment]
this will be addressed in #2008
