### ISSUE TITLE
[bug]: vault card indicates late rewards when they are still within bounds 

### ISSUE THREAD

**Issue by axejintao** [Badger-Finance/v2-ui#1988]
# Summary

Since cycle is 2 hours, we should only report late rewards post 2 hours ish (or orange slightly over) 

![image](https://user-images.githubusercontent.com/6101512/161388315-076ba4fb-df18-45bd-ab25-83f190a9fa1d.png)

Reporting late cycles (pic taken w/ 1h 52m into cycle)

**Comment by axejintao** [comment]
Putting on hold actually this may have been my browser.

**Comment by eliobricenov** [comment]
closing as this was no longer reproduced
