### ISSUE TITLE
Vaults icons middle aligned with text

### ISSUE THREAD

**Issue by DesignTheBlock** [Badger-Finance/v2-ui#1992]
When there are no tags below the tokens icons, the vaults icons should be middle aligned with the 2 lines of text.
<img width="757" alt="Screenshot 2022-04-05 at 9 53 15 AM" src="https://user-images.githubusercontent.com/59993416/161663742-31f44b78-fb3c-447d-8481-5bfbb565bfda.png">

**Comment by eliobricenov** [comment]
closing as this is no longer applicable.
