### ISSUE TITLE
[bug]: 15% fee on votes not shown in bveCVX vault page -users pointing it out

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/v2-ui#2092]
### Contact Details

Tritium or sbhk#9535

### What happened?

The current bveCVX vault page only shows 0.1% withdraw fee and 0% performance fee.

In fact bveCVX also charges the following fees on voting/bribing:

5% DAO Fee
5% bveCVX liqudity fee
5% Voting for wbtc/BADGER

At simplest this should be expressed as:

`fees on voting and bribe processing: 15%`

**bveCVX is in focus it would be good to get this fixed **
Docs were also wrong, updating those. 

### Version

current

### Relevant log output

```shell
no log
```

**Comment by axejintao** [comment]
resovled
