### ISSUE TITLE
[bug]: UI does not show proper fees available for withdraw

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/v2-ui#2093]
### Contact Details

Tritium

### What happened?

Right now the UI reports the tokens available for withdraw as those available in the stgrategy.  I think.

In fact, here is how withdraw availability works.

Unlocked tokens could be in the Vault, The stratgey, or in the locker(there should be functions in the strategy to see this)

The tokens available for withdraw display should reflect the sum all tokens available in the locker, the strat or the vault.

### Version

current

**Comment by axejintao** [comment]
resolved
