### ISSUE TITLE
[feat. request]: New Sett details page for influence vaults (bveCVX/graviAURA)

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/v2-ui#2107]
_NOTE: Your feature may already be requested!
Please search on the [issue tracker](../) before creating one._

## Summary (Required)

Please create this sett detail page for bveCVX.  I have already talked to @axejintao about getting the additional details in the API.

The fees, rewards frequency and text details sections should at all best just be free html text that can easily be edited in separate files.  Same with the info bubbles.  You can talk to @wasabiboat @ZKProf and I about text details.  Please open a group when you start work for questions so everyone has visability

Figma:https://www.figma.com/proto/2VVZaSQp7Rm8EwVfS50kCp/badger-scratch?page-id=0%3A1&node-id=20%3A1654&viewport=115%2C67%2C0.43&scaling=min-zoom&starting-point-node-id=20%3A1654

## Request Metrics (Required)

Rate how the level of importance of the feature, effort and and risk associated

| Metric   | Rating |
| -------- | ------ |
| Priority |    High    | - Live by june 29th
| Effort   |     Medium   |
| Risk     |     Medium   | - bveCVX is in focus, needs to be right by the 29th. 

_Options: low, medium, high_

<br/>
<br/>

## Documentation (optional)
Figma: https://www.figma.com/proto/2VVZaSQp7Rm8EwVfS50kCp/badger-scratch?page-id=0%3A1&node-id=20%3A1654&viewport=115%2C67%2C0.43&scaling=min-zoom&starting-point-node-id=20%3A1654

**Comment by axejintao** [comment]
completed
