### ISSUE TITLE
[bug]: Ensure we always show proper available blanace on influence valuts (graviAURA, bveCVX and any future vaults that manage locking)

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/v2-ui#2221]
### Contact Details

tritium#0069

### What happened?

bveOXD is not showing proper available
#2093 handles this for bveCVX.  This should be generalized across any and all influence vaults and semi-liquid lockers.

It should be checked as part of the QA process when making changes to the frontend.

### Version

current

### What browsers are you seeing the problem on?

Chrome, Brave

### Relevant log output

```shell
Just look at graviAURA, no available.  

On bveOXD available is wrong as it does not look in the strat and the locker.
```

**Comment by axejintao** [comment]
closed, will revist these on further bug reports in that repo
