### ISSUE TITLE
[bug]: Rename proj yields to spot yields in beta as this is what is shown

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/v2-ui#2229]
### Contact Details

tritium#0069

### What happened?

beta.badger.finance currently lists the vault 1.5 onchain yields as Proj./ projected
<img width="487" alt="image" src="https://user-images.githubusercontent.com/11885129/180784865-59169983-33a6-4a3a-ad69-919dbac864fe.png">
Note that the yields actually being shown are Spot yields.  Projected yields would have to match the projected yields on AURA which requires more math and we don't need to show.

Please rename Proj. and Projected yields to Spot.

Also please verify if this is an APY or APR number that is being shown, if APY perhaps mention the compounding frequency somewhere. 

### Version

beta

### What browsers are you seeing the problem on?

Brave

**Comment by axejintao** [comment]
declined
