### ISSUE TITLE
[bug]: Visual Bug, overflow on New Vault marker on APY

### ISSUE THREAD

**Issue by mitche50** [Badger-Finance/v2-ui#2246]
### Contact Details

mitche50

### What happened?

The "New Vault" display on beta.badger.com for vaults without significant history is overflowing.

![image](https://user-images.githubusercontent.com/6303774/181835587-9dc9e89e-d90b-4ffb-a733-620227aab0f9.png)

### Version

beta.badger.com

### What browsers are you seeing the problem on?

Firefox

**Comment by eliobricenov** [comment]
fixed in https://github.com/Badger-Finance/v2-ui/pull/2247
