### ISSUE TITLE
[bug]: WalletConnect Beta failure

### ISSUE THREAD

**Issue by mrbasado** [Badger-Finance/v2-ui#2255]
### What happened?

Moved from: https://github.com/Badger-Finance/badger-api/issues/1399
Reported on: 2022-08-05T05:05:35.749000+00:00
Bug Description:
User not able to connect their wallet through WalletConnect to the https://beta.badger.com/ app successfully.

Attachments:
content_type: image/png
filename: unknown.png
height: 163
id: 1004978457446449172
proxy_url: https://media.discordapp.net/attachments/863051342436499498/1004978457446449172/unknown.png
size: 108084
url: https://cdn.discordapp.com/attachments/863051342436499498/1004978457446449172/unknown.png
width: 524

### Version

Beta

**Comment by axejintao** [comment]
https://github.com/Badger-Finance/v2-ui/issues/2259
closing as duplicate

**Comment by axejintao** [comment]
updated due to out of date rpc
