### ISSUE TITLE
[feat. request]: BETA - Do not show badger boost page as default page

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/v2-ui#2271]
## Summary (Required)

Right now on many setts (everything other than influence vaults. I think) the Badger Boost page shows up when you click on the sett and go to the detail view.  In many cases the boost view shows a flat line as the sett has no badger emissions.

One of the biggest visable upgrades in the new site is the Vault Value view.  Suggest showing that first on all sets except for bveCVX and graviAURA where we have custom detail page..

Example:

https://beta.badger.com/vault/aura-aurabal?chain=ethereum
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/11885129/183931942-6e14de57-75dd-4b82-98e3-3699b80f26fd.png">

<br/>
<br/>
<br/>

## Request Metrics (Required)

Rate how the level of importance of the feature, effort and and risk associated

| Metric   | Rating |
| -------- | ------ |
| Priority |  Recommend before beta goes live      |
| Effort   |    Low    |
| Risk     |     Low   |

_Options: low, medium, high_

<br/>
<br/>

## Documentation (optional)

Add any supporting documentation, proposed API responses, interaction diagrams etc.
<br/>
<br/>

## Resources (optional)

Add any new or updated resource requirements for the system
<br/>
<br/>

**Comment by mrbasado** [comment]
flat boosted graphs were a bug so those are removed from these non-boosted vaults
