### ISSUE TITLE
feat: support geyser withdraws

### ISSUE THREAD

**Issue by axejintao** [Badger-Finance/v2-ui#2290]
# Summary

Badger launched with the requirement for depositing into geysers to receive tokens at launch. Allow users to withdraw from geysers in the application if they have balances

This ticket is blocked until https://github.com/Badger-Finance/badger-sdk/issues/246 is ready and released.

## Requirements

- if a user connects to the app and has tokens deposited into geysers - display a warning with a redirect or modal prompt to withdraw
- utilize same withdraw modals (without any fees)
- always prompt to withdraw from the geyser - annoy the shit out of them and do not remove it from the screen unless they withdraw

## Notes

- sdk will support geyser balances look ups 
- sdk will support withdraws

**Comment by mrbasado** [comment]
This is the last piece of backwards compatibility to close out the legacy app, can reopen if we want to get rid of the legacy app
