### ISSUE TITLE
[bug]: graviAURA reward modal not showing line for emitted graviAURA

### ISSUE THREAD

**Issue by okra-sf** [Badger-Finance/v2-ui#2295]
### Contact Details

Discord okra_sf

### What happened?

Expecting to see a line in the reward modal for emitted graviAURA, like the Badger line there.  Also the number is really high on the Badger given it should be 25% of the total bribes returned.  So not clear what is fully off, but certainly the missing line for the graviAURA

**EVIDENCE**:
![image](https://user-images.githubusercontent.com/110788460/185512863-9213a653-4b1d-4385-bcd7-79647ee4a5bb.png)

### Version

app.badger.com

### What browsers are you seeing the problem on?

Chrome

**Comment by okra-sf** [comment]
hey team, as per discord, beta certainly better in that it has the 4 expected reward lines.  ratio of badger & gravi not what I'd expect, but the special distribution from the digg lp gravi could explain this

**Comment by mrbasado** [comment]
think this was resolved, closing can reopen if this isn't the case
