### ISSUE TITLE
[feat. request]: Lets get the graivaura graph going

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/v2-ui#2298]
## Summary (Required)

The graviaura sett detail page https://app.badger.com/vault/aura-graviaura?chain=ethereum, was recently updated to include the new influence style view.  At the moment the graph says Comming Soon.

<img width="858" alt="image" src="https://user-images.githubusercontent.com/11885129/185670700-d13ee443-1567-47e6-9d12-e3627c8ba829.png">

To make the discussion more clear below, here is how the graph should look (based on bveCVX, but we are only on round 5):
<img width="813" alt="image" src="https://user-images.githubusercontent.com/11885129/185671981-9d52eecc-5637-47d4-a7e6-8128ab036ca8.png">

Lots is going on with graviAURA yields right now and they are big.  People want to be able to undertstand, and this graph is the best way we have to do it.  It would be nice if we could get it working soon after the next bribe payout, which should take place next friday.

I believe the main issue is the fact that the first rounds were all quite irregular and weird and charting them all takes a huge amount of investigation and exception handling.  That being said, from round 5 forward things should be regular.  Perhaps it would be reasonably easy to get this graph working starting from the round 5 emissions so we can ignore the mess bootstrapping mess.

From round 5 forward there should be the following reward streams per round:

1: underlying rewards, expressed as autocompounding of the auraBAL vault every 5 days or so based on harvests.
2: Bribe payouts of graviAURA and BADGER which should be paid out each 2 weeks on Friday (following the end of a voting round and successful processing of the bribes).  
3: The bribe payouts are for the round that has already finished, which starts on the Wednesday the week before the payout.

So for example.  Round 5 Started on August 18th at 00:00 UTC.   It will end exactly 2 weeks later on the 31st at midnight UTC when round 6 begins.  During that timeframe, there should be 2 or 3 harvests, and some bribe payouts.  The bribe payouts are likely to come in sometime between the 26th and the 28th (in the second half of the round)

<br/>
<br/>
<br/>

## Request Metrics (Required)

Rate how the level of importance of the feature, effort and and risk associated

| Metric   | Rating |
| -------- | ------ |
| Priority |    High    |
| Effort   |        |
| Risk     |        |

_Options: low, medium, high_

<br/>
<br/>

## Documentation (optional)

Feel free to contact tritium for more info. 
<br/>
<br/>

## Resources (optional)

Add any new or updated resource requirements for the system
<br/>
<br/>

**Comment by axejintao** [comment]
> it should show accurate information from round 5 and beyond, we can ignore the earlier rounds due to irregularity

from @dapp-whisperer

**Comment by mrbasado** [comment]
forgot to update on the ticket: we have so data issues on this and JIntao is working on some fixes in v3 to address these and get some of the missing data on it. we hope these changes will allow us to get this out by the 9th or so

**Comment by axejintao** [comment]
reassigned, data is available - should be sufficient to start the graphing data i believe
sans the missing badger distro that will need to be manually added the endpoint can be used
