### ISSUE TITLE
refactor: wind down bsc + polygon options

### ISSUE THREAD

**Issue by axejintao** [Badger-Finance/v2-ui#2333]
# Summary

BSC + Polygon deployments are not used (all deprecated vaults) and they do not need to be currently supports (displayed) in the UI. 

## Requirements

- instate a 2 week warning period that vaults on bsc + eth will be winding down
- after the warning, remove the options to change to polygon + bsc networks
- if a user is connected to polygon or bsc they should be prompted to swap chains to eth

## Blockers

- #2290 

This ticket should not be completed until geyser support is available in the app. Once it is available, legacy app should transition instead to an application supporting all previous chains focusing on deprecated only vaults - or vaults user has funds allocated to.

**Comment by mrbasado** [comment]
add a notice on vault list page that this is being closed down by Nov 1st 2022 (BSC)
