### ISSUE TITLE
refactor: periodically refresh user data

### ISSUE THREAD

**Issue by axejintao** [Badger-Finance/v2-ui#2337]
# Summary

Users sometimes leave the Badger App open - as it does not periodically refresh data like the user claim data sometimes this leads to 'Invalid Cycle' issues, delayed or missed portfolio updates, and also allows users to, for instance, deposit into a vault liquidity pool and have the app update balances and reflect a user can deposit without having them hard refresh. 

## Requirements

- refresh user data every x seconds, identify a good timeframe (maybe 15-30 seonds?) if on an rpc wallet maybe 5 minutes

**Comment by mrbasado** [comment]
I misunderstood the goal of this ticket, and this problem isn't solved fully: " 'Invalid Cycle' issues" still occurs Screen Shot 2022-09-20 at 10.27.49 PM

**Comment by mrbasado** [comment]
currently refreshes balances() only needs to refresh user rewards @mranilrai
