### ISSUE TITLE
bug: cvxcrv strategy diagram links to dead site

### ISSUE THREAD

**Issue by axejintao** [Badger-Finance/v2-ui#2339]
# Summary

https://app.badger.com/vault/convex-cvxcrv?chain=ethereum

Clicking startegy diagram redirects to a no longer supporter site. 

## Requirements 

- update all wiki links with their equivalents, or remove and log if a discrepancy is occurred (i.e. missing link <> digram)

**Comment by mrbasado** [comment]
@will-i-am24 in discord decided we are just going to remove this link as the user guide has this information already
