### ISSUE TITLE
Digg page hangs on brave

### ISSUE THREAD

**Issue by mitche50** [Badger-Finance/v2-ui#2355]
Reported on: 2022-09-10T07:32:13.912000+00:00
Bug Description:
Dapp hangs when you click into Digg vault. metamask on brave.

Attachments:
content_type: image/jpeg
filename: sc.jpg
height: 559
id: 1018061321989795840
proxy_url: https://media.discordapp.net/attachments/863051269337907210/1018061321989795840/sc.jpg
size: 145263
url: https://cdn.discordapp.com/attachments/863051269337907210/1018061321989795840/sc.jpg
width: 1339

**Comment by mrbasado** [comment]
this is legit @mranilrai
