### ISSUE TITLE
refactor(apy evolution): utilize gross apr snapshot field

### ISSUE THREAD

**Issue by axejintao** [Badger-Finance/v2-ui#2357]
# Summary

Currently charts are using the historic APR, not the gross historic APR - this is not in line with requirements from the APY evolution

## Requirements

- utilize (where available) grossApr field
- if not available, use the strategy info to derive the gross apr

**Comment by mrbasado** [comment]
@axejintao think we can close this as won't do because we are still on net. we can reopen if that is not the case
