### ISSUE TITLE
bug: Cant deposit LP into vault

### ISSUE THREAD

**Issue by mitche50** [Badger-Finance/v2-ui#2424]
Reported on: 2022-10-18T03:00:19.811000+00:00
Bug Description:
User using MetaMask and getting a "deposit transaction cancelled by user" the moment they try to deposit their tokens in the Convex - renBTC/wBTC vault +

Attachments:
content_type: image/png
filename: unknown.png
height: 194
id: 1031763634491248640
proxy_url: https://media.discordapp.net/attachments/863051269337907210/1031763634491248640/unknown.png
size: 12992
url: https://cdn.discordapp.com/attachments/863051269337907210/1031763634491248640/unknown.png
width: 666

content_type: image/png
filename: unknown.png
height: 816
id: 1031763634898075688
proxy_url: https://media.discordapp.net/attachments/863051269337907210/1031763634898075688/unknown.png
size: 57993
url: https://cdn.discordapp.com/attachments/863051269337907210/1031763634898075688/unknown.png
width: 1358

**Comment by mranilrai** [comment]
Regarding the `ibBTC minting and redeeming pages don't load the asset menu to select which asset to mint with/redeem to`, I did verify the asset menu and it's loading fine on prod & beta.
|||
|---|---|
|<img width="827" alt="Screenshot 2022-10-20 at 7 27 02 PM" src="https://user-images.githubusercontent.com/4344538/196969425-b9c32105-901e-408b-ad0f-eda9ed3dc628.png">|<img width="821" alt="Screenshot 2022-10-20 at 7 26 55 PM" src="https://user-images.githubusercontent.com/4344538/196969452-53786ce4-5738-4fe8-bcc1-5ef5648216a2.png">|
