### ISSUE TITLE
bug: ibbtc vault does not let users deposit tokens in lp

### ISSUE THREAD

**Issue by axejintao** [Badger-Finance/v2-ui#2435]
# Summary

![image](https://user-images.githubusercontent.com/6101512/197554108-c1cdb0a1-00cb-4758-8860-14fcb5a13e6a.png)

ibBTC vault has a deposit modal to accommodate WBTC, SBTC, renBTC, wibBTC deposits. This vault should check if the user has any tokens before deeming that the user needs to go to curve to deposit. 

As the flow is preserved for 3/4 tokens this is not a blocker, but we should leverage our zap to avoid confusion around wrapped ibBTC.

**Comment by mrbasado** [comment]
won't do - jintao
