### ISSUE TITLE
The 'Deposit Curve LP To Badger' button in https://wrap.badger.com/ also redirects to a broken link:

### ISSUE THREAD

**Issue by mitche50** [Badger-Finance/v2-ui#2453]
Reported on: 2022-11-01T19:09:58.139000+00:00
Bug Description:
The 'Deposit Curve LP To Badger' button in https://wrap.badger.com/ also redirects to a broken link: it sends users to https://app.badger.com/setts/ibbtc-crvsbtc-lp, instead of https://app.badger.com/vault/convex-ibbtc-crvsbtc?chain=ethereum

Attachments:
content_type: image/png
filename: unknown.png
height: 147
id: 1037081082807460001
proxy_url: https://media.discordapp.net/attachments/863051269337907210/1037081082807460001/unknown.png
size: 8090
url: https://cdn.discordapp.com/attachments/863051269337907210/1037081082807460001/unknown.png
width: 235

**Comment by mrbasado** [comment]
@mranilrai repo: https://github.com/Badger-Finance/wibbtc-app
