### ISSUE TITLE
User getting an error when trying to claim old rewards on Arbitrum.

### ISSUE THREAD

**Issue by mitche50** [Badger-Finance/v2-ui#2498]
Reported on: 2022-12-16T18:10:26.292000+00:00
Bug Description:
User getting an error when trying to claim old rewards on Arbitrum.

Attachments:
content_type: image/png
filename: image.png
height: 577
id: 1053373554881740880
proxy_url: https://media.discordapp.net/attachments/863051269337907210/1053373554881740880/image.png
size: 76609
url: https://cdn.discordapp.com/attachments/863051269337907210/1053373554881740880/image.png
width: 1115

**Comment by mrbasado** [comment]
fixed, contract didn't have funds. treasury sent funds a script was made to detect total rewards left for users to claim on arb
